name: Build Everything
on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  build-fedora:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    container: 
      image: quay.io/fedora-ostree-desktops/buildroot:latest
      options: --privileged
    steps:
      - name: Clone repository
        run: git clone --branch f38 --depth 1 --single-branch https://gitlab.com/fedora/ostree/ci-test.git .
      - name: Build image
        run: just compose-image kinoite
      - name: Upload image
        run: |
          skopeo login --username "${{ github.actor }}" --password "${{ github.token }}" ghcr.io
          skopeo copy --retry-times 3 "oci-archive:fedora-kinoite.ociarchive" "docker://ghcr.io/${{ github.repository_owner }}/fedora-kinoite:38"
  build-ublue:
    needs: build-fedora
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          repository: ublue-os/main
      - name: Modify image source
        run: sed -i 's,^ARG BASE_IMAGE="quay.io/fedora-ostree-desktops/,ARG BASE_IMAGE="ghcr.io/${{ github.repository_owner }}/fedora-,g' ./Containerfile
      - name: Build image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            ./Containerfile
          image: ublueos-kinoite-main
          tags: 38 latest
          build-args: |
            IMAGE_NAME=kinoite-main
            SOURCE_IMAGE=kinoite
            FEDORA_MAJOR_VERSION=38
          oci: false
          extra-args: |
            --target=main
      - name: Upload image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
          extra-args: |
            --disable-content-trust
  build-bazzite:
    needs: build-ublue
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          repository: ublue-os/bazzite
      - name: Modify image source
        run: sed -i 's,^ARG BASE_IMAGE="ghcr.io/ublue-os/,ARG BASE_IMAGE="ghcr.io/${{ github.repository_owner }}/ublueos-,g' ./Containerfile
      - name: Build image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            ./Containerfile
          image: ublueos-bazzite-deck
          tags: 38 latest
          build-args: |
            IMAGE_NAME=bazzite-deck
            IMAGE_FLAVOR=main
            BASE_IMAGE_NAME=kinoite
            FEDORA_MAJOR_VERSION=38
          oci: false
          extra-args: |
            --target=bazzite-deck
      - name: Upload image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
          extra-args: |
            --disable-content-trust
